### ISSUE TITLE
Are file sizes in KB?

### ISSUE THREAD

**Issue by osukhoroslov** [workflowhub/pegasus-traces#1]
Please confirm whether the file sizes in provided instances are specified in KB (as stated WfCommons JSON Schema).
I'm asking because in [this paper](https://rafaelsilva.com/files/publications/casanova2022jsspp.pdf) it is stated that the footprint of [the Epigenomics instance with 1095 tasks](https://github.com/wfcommons/pegasus-instances/blob/master/epigenomics/chameleon-cloud/epigenomics-chameleon-ilmn-4seq-50k-001.json) is 8.25 GB.

![изображение](https://user-images.githubusercontent.com/1322460/229367848-b7329fed-4d73-4b9e-aee0-9bcd7824cb88.png)

However, assuming that the file sizes are in KB, the footprint (sum of all files) should be 1000 times more - 8257 GB.
For example, only two files of the first task already amount for 280 GB.

![изображение](https://user-images.githubusercontent.com/1322460/229368070-3ea9355d-3864-452b-b1cd-4d51804fdf38.png)

So either the file sizes are specified in bytes (do not conform to Schema) or there is mistake in the paper. Please clarify.

**Comment by osukhoroslov** [comment]
@rafaelfsilva @henricasanova please respond

**Comment by henricasanova** [comment]
Hi, sorry, I think each one of us thought the other was about to respond.  Yes, the data is in KB, and that paper mistakenly assumed bytes when coming up with the data in the table.   An extended version of this paper is being submitted with that error corrected.

**Comment by osukhoroslov** [comment]
@henricasanova thanks for clarifying this

**Comment by henricasanova** [comment]
@osukhoroslov After investigating further, we found a bug in the Pegasus log parser in WfCommons. So, the documentation specifies that all file sizes are in KB, BUT for the Pegasus workflow instances, instead they are in byte!  Sorry for the confusion/inconvenience.   

Note that we are in the process of modifying the JSON schema so that all file names make the units explicit (e.g., "size_in_bytes") and using only "base" units (bytes, seconds).  This will be WfFormat 1.4, coming soon.

**Comment by osukhoroslov** [comment]
Great you sorted this out, thanks!
